// <auto-generated />
namespace ShoppinSite.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DroptableUserGroupandGroupalsoaddedforeignkeyinroleDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DroptableUserGroupandGroupalsoaddedforeignkeyinroleDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "202006131419073_Drop table UserGroup and Group also added foreign key in roleDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
