// <auto-generated />
namespace ShoppinSite.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class userchanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userchanged));
        
        string IMigrationMetadata.Id
        {
            get { return "202011281520078_user changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
